### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by ErikElliott-ynp** [hankc97/robinhood#3]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [ ] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by ErikElliott-ynp** [comment]
1. signup image sizing
2. signup form spacing
3. Hover color darken on buttons
4. img tage styling
5. inputs background-color to white and green outline on focus
6. splash page as auth route

**Comment by ErikElliott-ynp** [comment]
7. Demo user

**Comment by juliawang105** [comment]
1. Font needs to be changed to match site
2. Add padding for input fields- the placeholders are too close to the left border 
3. Hover color darken on buttons
4. Signup/Login pages should include links that take me back to the home page as well as links to the other forms
